fix: select of BinaryExpressions
* sqlalchemy.exc.ArgumentError: Column expression, FROM clause, or other
  columns clause element expected, got
  [<sqlalchemy.sql.elements.BinaryExpression object at 0x7fa3a0>,
  <sqlalchemy.sql.elements.BinaryExpression object at 0x7fa3ad246690>].
  Did you mean to say select(<sqlalchemy.sql.elements.BinaryExpression
  object at 0x7fa3b1145c10>, <sqly.sql.elements.BinaryExpression object at
  0x7fa3ad246690>)

  don't give the array to the select but give the elements to the select
  method

* AttributeError: 'Engine' object has no attribute 'execute' -> change
  to session

* TypeError: scoped_session.execute() got an unexpected keyword argument
  'a' -> change to dict